ALTER TABLE UserProfile DROP COLUMN Id
ALTER TABLE UserProfile ADD id INT IDENTITY PRIMARY KEY NOT NULL

ALTER TABLE Project DROP COLUMN Id
ALTER TABLE Project ADD id INT IDENTITY PRIMARY KEY NOT NULL

ALTER TABLE Room DROP COLUMN Id
ALTER TABLE Room ADD id INT IDENTITY PRIMARY KEY NOT NULL

ALTER TABLE TaskCategory DROP COLUMN Id
ALTER TABLE TaskCategory ADD id INT IDENTITY PRIMARY KEY NOT NULL

ALTER TABLE Task DROP COLUMN Id
ALTER TABLE Task ADD id INT IDENTITY PRIMARY KEY NOT NULL

ALTER TABLE TaskNote DROP COLUMN Id
ALTER TABLE TaskNote ADD id INT IDENTITY PRIMARY KEY NOT NULL

ALTER TABLE Project ADD CONSTRAINT FK_Project_UserProfile FOREIGN KEY (userProfileId) REFERENCES dbo.UserProfile (id)

ALTER TABLE Task ADD CONSTRAINT FK_Task_Project FOREIGN KEY (projectId) REFERENCES dbo.Project (id)

ALTER TABLE Task ADD CONSTRAINT FK_Task_Room FOREIGN KEY (roomId) REFERENCES dbo.Room (id)

ALTER TABLE Task ADD CONSTRAINT FK_Task_TaskCategory FOREIGN KEY (taskCategoryId) REFERENCES dbo.TaskCategory (id)

ALTER TABLE TaskNote ADD CONSTRAINT FK_TaskNote_Task FOREIGN KEY (taskId) REFERENCES dbo.Task (id)

